[package]
name = "sfml"
description = "Rust binding for sfml"
version = "0.11.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]

documentation = "https://crates.fyi/crates/sfml/0.11.0/"
repository = "https://github.com/jeremyletang/rust-sfml"
license = "zlib-acknowledgement"

[dependencies]
libc = "0.2.2"
bitflags = "0.5"

[dependencies.sfml-types]
path = "sfml-types"
version = "0.1.0"

[dependencies.csfml-system-sys]
path = "csfml-system-sys"
version = "0.1.0"

[dependencies.csfml-window-sys]
path = "csfml-window-sys"
version = "0.1.0"

[dependencies.csfml-graphics-sys]
path = "csfml-graphics-sys"
version = "0.1.0"

[dependencies.csfml-audio-sys]
path = "csfml-audio-sys"
version = "0.1.0"

[dependencies.csfml-network-sys]
path = "csfml-network-sys"
version = "0.1.0"

[dev-dependencies]
rand = "0.3"

[lib]
name = "sfml"
crate-type = ["dylib", "rlib"]
