[package]
name = "sfml"
description = "Rust binding for sfml"
version = "0.10.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]

documentation = "http://www.rust-sfml.org/doc/rsfml/index.html"
homepage = "http://www.rust-sfml.org/"
repository = "https://github.com/jeremyletang/rust-sfml"
license = "zlib-acknowledgement"

[dependencies]
libc = "0.2.2"
bitflags = ">=0.1"

[dependencies.sfml-types]
path = "sfml-types"

[dependencies.csfml-system-sys]
path = "csfml-system-sys"

[dependencies.csfml-window-sys]
path = "csfml-window-sys"

[dependencies.csfml-graphics-sys]
path = "csfml-graphics-sys"

[dependencies.csfml-audio-sys]
path = "csfml-audio-sys"

[dependencies.csfml-network-sys]
path = "csfml-network-sys"

[dev-dependencies]
rand = ">=0.2.0"

[lib]
name = "sfml"
crate-type = ["dylib", "rlib"]
