[package]

name = "rust-sfml"
description = "Rust binding for sfml"
version = "0.9.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]

[dependencies]
rand = ">=0.2.0"
libc = ">=0.1.5"

[lib]

name = "rsfml"
crate-type = ["dylib", "rlib"]
