[package]
name = "csfml-audio-sys"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
links = "csfml-audio"
build = "build.rs"

[dependencies]
libc = "0.1.10"

[dependencies.sfml-types]
path = "../sfml-types"

[dependencies.csfml-system-sys]
path = "../csfml-system-sys"
