[package]
name = "csfml-window-sys"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
links = "csfml-window"
build = "build.rs"

[dependencies]
libc = "0.2.2"

[dependencies.sfml-types]
path = "../sfml-types"

[dependencies.csfml-system-sys]
path = "../csfml-system-sys"
